-- 1
SELECT @@autocommit;
SET autocommit=0;
-- 2
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
-- 3
LOCK TABLES CLIENTE WRITE;
LOCK TABLES PELICULA WRITE;
LOCK TABLES FACTURA READ;
LOCK TABLES DETALLEFACTURA READ;
LOCK TABLES PRESTAMO READ;
-- 4
START transaction;
-- 5
INSERT INTO PRESTAMO VALUES((SELECT CodPeli FROM PELICULA WHERE Titulo ="Guardianes de la galaxia"),1,CURDATE(),(SELECT DNI FROM CLIENTE WHERE Nombre="Maria Casas"));
INSERT INTO FACTURA VALUES(5,CURDATE(),4.5,(SELECT DNI FROM CLIENTE WHERE Nombre="Maria Casas"));
INSERT INTO FACTURA VALUES(5,CURDATE(),6,(SELECT DNI FROM CLIENTE WHERE Nombre="Maria Casas"));
INSERT INTO DETALLEFACTURA VALUES(5,1,"Alquiler",4.5,1);
INSERT INTO DETALLEFACTURA VALUES(5,2,"Palomitas",3,2);
-- 6
COMMIT;
-- 7
UNLOCK TABLES;